### ISSUE TITLE
Add React Router

### ISSUE THREAD

**Issue by PabloFer13** [cancunDevs/omiqroo-front#2]
Add routing to the project using React Router 4

**Comment by yoniihdc** [comment]
## Acceptance Criteria:
Creates the following paths:
* Inicio (`/`)
* Convocatoria (`/convocatoria`)
* Resultados (`/resultados`)
* Material (`/material`)
* Anuncios (`/anuncios`)
* Contacto (`/contacto`)

At the moment all pages can use the same component just to display wich page is, ie:

`Bienvenido a la pagina: $pagina` where `$pagina` is the name of the section selected
