### ISSUE TITLE
Home - Component

### ISSUE THREAD

**Issue by yoniihdc** [cancunDevs/omiqroo-front#5]
## Acceptance Criteria

Homepage with information about OMI, and OMI QROO  that displays the official poster from the Mexican olympiad in informatics as well as a contact form to keep tracking from users requesting information.

*NOTE:* Contact Form can be another component to be reused in the contact page. Depends on #6

**Comment by jonathanperazawl** [comment]
Redesign changes:
- Official poster removed from the homepage
- News feeds added to the homepage
